### ISSUE TITLE
Todo for Oct 6

### ISSUE THREAD

**Issue by mahmudhera** [mahmudhera/krispmer-expreminets#5]
- [x] Generate gene and intergenic targets for mouse
- [x] Generate duplicated region targets
- [x] Run krispmer on al targets
- [x] Generate the diagonal plot for mouse
- [ ] Generate gene and intergenic targets for humans
- [ ] Generate duplicated region targets
- [ ] Run krispmer on al targets
- [ ] Generate the diagonal plot for human targets 
- [ ] Maybe next one or two comparisons
